apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-ingress
  namespace: prod
  annotations:
    argocd.argoproj.io/tracking-id: nextunitech-prod:networking.k8s.io/Ingress:prod/chatbot-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.nextunitech.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: chatbot-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chatbot-frontend
                port:
                  number: 8080
    - host: nextunitech.com          # <── add this block
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: chatbot-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chatbot-frontend
                port:
                  number: 8080
